using System.Text;
using HaStagingConsole.Models;

namespace HaStagingConsole.Services;

public sealed class EnvWriter(KitPaths paths)
{
    public void WriteKitEnv(OnboardingState state, string? stagingHaContainer = null)
    {
        var lines = EnvFile.Read(paths.EnvFile);

        lines["HA_CONFIG_REPO"] = state.Paths.HaConfigRepo;
        lines["HA_STAGING_CONFIG"] = state.Paths.HaStagingConfig;
        lines["SIDECAR_DATA"] = state.Paths.SidecarData;
        lines["MIRROR_DATA"] = state.Paths.MirrorData;
        lines["HA_BRANCH"] = state.Paths.HaBranch;
        lines["PROD_HA_URL"] = state.Prod.Url;
        lines["STAGING_HA_URL"] = state.Staging.Url;
        if (!string.IsNullOrWhiteSpace(state.Prod.SshTarget))
        {
            lines["HA_SECRETS"] = state.Prod.SshTarget.TrimEnd('/') + "/secrets.yaml";
            lines["HA_STORAGE"] = state.Prod.SshTarget.TrimEnd('/') + "/.storage/";
        }
        if (state.Mirror.Enabled && !string.IsNullOrWhiteSpace(state.Mirror.ProdMqttHost))
        {
            lines["PROD_MQTT_HOST"] = state.Mirror.ProdMqttHost;
            lines["PROD_MQTT_PORT"] = state.Mirror.ProdMqttPort.ToString();
        }
        if (state.Mirror.Enabled && !string.IsNullOrWhiteSpace(state.Mirror.StagingMqttBrokerHost))
        {
            lines["STAGING_MQTT_BROKER"] = state.Mirror.StagingMqttBrokerHost.Trim();
            lines["STAGING_MQTT_PORT"] = state.Mirror.StagingMqttPort.ToString();
        }
        if (!string.IsNullOrWhiteSpace(stagingHaContainer))
            lines["STAGING_HA_CONTAINER"] = stagingHaContainer.Trim();

        var order = new[]
        {
            "HA_CONFIG_REPO", "HA_STAGING_CONFIG", "SIDECAR_DATA", "MIRROR_DATA",
            "PROD_HA_URL", "HA_SECRETS", "HA_STORAGE", "STAGING_HA_URL", "HA_BRANCH",
            "PROD_MQTT_HOST", "PROD_MQTT_PORT", "STAGING_MQTT_BROKER", "STAGING_MQTT_PORT", "KIT_MQTT_BROKER", "MIRROR_PORT", "CONSOLE_PORT", "STAGING_HA_CONTAINER"
        };

        var sb = new StringBuilder();
        sb.AppendLine("# Generated/updated by ha-staging-console onboarding");
        var written = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var key in order)
        {
            if (!lines.TryGetValue(key, out var value))
                continue;
            sb.AppendLine($"{key}={value}");
            written.Add(key);
        }
        foreach (var kv in lines.Where(kv => !written.Contains(kv.Key)).OrderBy(kv => kv.Key))
            sb.AppendLine($"{kv.Key}={kv.Value}");

        File.WriteAllText(paths.EnvFile, sb.ToString());
    }

    public void WriteSidecarConfig(OnboardingState state, SidecarIntervals? intervals = null)
    {
        Directory.CreateDirectory(paths.SidecarData);
        var kit = EnvFile.Read(paths.EnvFile);
        var poll = intervals?.PersonPollIntervalSeconds ?? 60;
        var storage = intervals?.StorageSyncIntervalSeconds ?? 86400;
        var applyOnStart = intervals?.ApplyOnStart ?? true;
        var skipStorage = intervals?.SkipStorageSync ?? false;
        var mqttBroker = !string.IsNullOrWhiteSpace(state.Mirror.StagingMqttBrokerHost)
            ? state.Mirror.StagingMqttBrokerHost.Trim()
            : kit.GetValueOrDefault("STAGING_MQTT_BROKER", "");
        var mqttPort = state.Mirror.StagingMqttPort > 0
            ? state.Mirror.StagingMqttPort
            : int.TryParse(kit.GetValueOrDefault("STAGING_MQTT_PORT", "1883"), out var p) ? p : 1883;
        var haSecrets = !string.IsNullOrWhiteSpace(state.Prod.SshTarget)
            ? state.Prod.SshTarget.TrimEnd('/') + "/secrets.yaml"
            : kit.GetValueOrDefault("HA_SECRETS", "");
        var haStorage = !string.IsNullOrWhiteSpace(state.Prod.SshTarget)
            ? state.Prod.SshTarget.TrimEnd('/') + "/.storage/"
            : kit.GetValueOrDefault("HA_STORAGE", "");

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by ha-staging-console");
        sb.AppendLine("REPO_DIR=/repo");
        sb.AppendLine("HA_CONFIG=/ha-config");
        sb.AppendLine($"HA_BRANCH={state.Paths.HaBranch}");
        sb.AppendLine($"STAGING_HA_URL={state.Staging.Url}");
        sb.AppendLine($"PERSON_POLL_INTERVAL={poll}");
        sb.AppendLine($"STORAGE_SYNC_INTERVAL={storage}");
        sb.AppendLine($"APPLY_ON_START={(applyOnStart ? "1" : "auto")}");
        sb.AppendLine($"SKIP_STORAGE_SYNC={(skipStorage ? 1 : 0)}");
        sb.AppendLine("SECRETS_DIR=/sidecar-data/secrets");
        sb.AppendLine("SIDECAR_TEMPLATE=/sidecar/templates/packages-sidecar.yaml");
        sb.AppendLine($"STAGING_HA_TYPE={state.Topology.StagingHaType}");
        sb.AppendLine($"PROD_HA_TYPE={state.Topology.ProdHaType}");
        if (!string.IsNullOrWhiteSpace(haSecrets))
            sb.AppendLine($"HA_SECRETS={haSecrets}");
        if (!string.IsNullOrWhiteSpace(haStorage))
            sb.AppendLine($"HA_STORAGE={haStorage}");
        if (!string.IsNullOrWhiteSpace(mqttBroker))
        {
            sb.AppendLine($"STAGING_MQTT_BROKER={mqttBroker}");
            sb.AppendLine($"STAGING_MQTT_PORT={mqttPort}");
        }

        File.WriteAllText(paths.ConfigEnvFile, sb.ToString());
    }

    public void WriteTokenFile(string path, string url, string token)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, $"{url.TrimEnd('/')}\n{token.Trim()}\n");
        File.SetUnixFileMode(path, UnixFileMode.UserRead | UnixFileMode.UserWrite);
    }

    /// <summary>Update URL line when token is unchanged (e.g. user changed URL but left token blank).</summary>
    public void SyncTokenUrl(string path, string url)
    {
        if (!File.Exists(path))
            return;

        var lines = File.ReadAllLines(path);
        var existingToken = lines.ElementAtOrDefault(1)?.Trim();
        if (string.IsNullOrWhiteSpace(existingToken))
            return;

        WriteTokenFile(path, url, existingToken);
    }

    public void WriteSshKey(string privateKey)
    {
        Directory.CreateDirectory(paths.SecretsDir);
        File.WriteAllText(paths.SshKeyFile, privateKey.Replace("\r\n", "\n").Trim() + "\n");
        File.SetUnixFileMode(paths.SshKeyFile, UnixFileMode.UserRead | UnixFileMode.UserWrite);
    }
}
