using System.Text;
using HaStagingConsole.Models;

namespace HaStagingConsole.Services;

public sealed class EnvWriter(KitPaths paths)
{
    public void WriteKitEnv(OnboardingState state)
    {
        var lines = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (File.Exists(paths.EnvFile))
        {
            foreach (var line in File.ReadAllLines(paths.EnvFile))
            {
                if (string.IsNullOrWhiteSpace(line) || line.TrimStart().StartsWith('#'))
                    continue;
                var idx = line.IndexOf('=');
                if (idx > 0)
                    lines[line[..idx].Trim()] = line[(idx + 1)..].Trim();
            }
        }

        lines["HA_CONFIG_REPO"] = state.Paths.HaConfigRepo;
        lines["HA_STAGING_CONFIG"] = state.Paths.HaStagingConfig;
        lines["SIDECAR_DATA"] = state.Paths.SidecarData;
        lines["MIRROR_DATA"] = state.Paths.MirrorData;
        lines["HA_BRANCH"] = state.Paths.HaBranch;
        lines["PROD_HA_URL"] = state.Prod.Url;
        lines["STAGING_HA_URL"] = state.Staging.Url;
        if (!string.IsNullOrWhiteSpace(state.Prod.SshTarget))
        {
            lines["HA_SECRETS"] = state.Prod.SshTarget.TrimEnd('/') + "/secrets.yaml";
            lines["HA_STORAGE"] = state.Prod.SshTarget.TrimEnd('/') + "/.storage/";
        }
        if (state.Mirror.Enabled && !string.IsNullOrWhiteSpace(state.Mirror.ProdMqttHost))
        {
            lines["PROD_MQTT_HOST"] = state.Mirror.ProdMqttHost;
            lines["PROD_MQTT_PORT"] = state.Mirror.ProdMqttPort.ToString();
        }

        var order = new[]
        {
            "HA_CONFIG_REPO", "HA_STAGING_CONFIG", "SIDECAR_DATA", "MIRROR_DATA",
            "PROD_HA_URL", "HA_SECRETS", "HA_STORAGE", "STAGING_HA_URL", "HA_BRANCH",
            "PROD_MQTT_HOST", "PROD_MQTT_PORT", "MIRROR_PORT", "CONSOLE_PORT"
        };

        var sb = new StringBuilder();
        sb.AppendLine("# Generated/updated by ha-staging-console onboarding");
        var written = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var key in order)
        {
            if (!lines.TryGetValue(key, out var value))
                continue;
            sb.AppendLine($"{key}={value}");
            written.Add(key);
        }
        foreach (var kv in lines.Where(kv => !written.Contains(kv.Key)).OrderBy(kv => kv.Key))
            sb.AppendLine($"{kv.Key}={kv.Value}");

        File.WriteAllText(paths.EnvFile, sb.ToString());
    }

    public void WriteSidecarConfig(OnboardingState state)
    {
        Directory.CreateDirectory(paths.SidecarData);
        var content = $"""
            # Generated by ha-staging-console onboarding
            REPO_DIR=/repo
            HA_CONFIG=/ha-config
            HA_BRANCH={state.Paths.HaBranch}
            STAGING_HA_URL={state.Staging.Url}
            PERSON_POLL_INTERVAL=60
            STORAGE_SYNC_INTERVAL=86400
            APPLY_ON_START=1
            SKIP_STORAGE_SYNC=0
            SECRETS_DIR=/sidecar-data/secrets
            SIDECAR_TEMPLATE=/sidecar/templates/packages-sidecar.yaml
            """;
        File.WriteAllText(paths.ConfigEnvFile, content);
    }

    public void WriteTokenFile(string path, string url, string token)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, $"{url.TrimEnd('/')}\n{token.Trim()}\n");
        File.SetUnixFileMode(path, UnixFileMode.UserRead | UnixFileMode.UserWrite);
    }

    public void WriteSshKey(string privateKey)
    {
        Directory.CreateDirectory(paths.SecretsDir);
        File.WriteAllText(paths.SshKeyFile, privateKey.Replace("\r\n", "\n").Trim() + "\n");
        File.SetUnixFileMode(paths.SshKeyFile, UnixFileMode.UserRead | UnixFileMode.UserWrite);
    }
}
